//user Auth action types
export const CREATE_USER_WITH_EMAIL_PASS = "CREATE_USER_WITH_EMAIL_PASS";
export const AUTH_STATUS_OBSERVER = "AUTH_STATUS_OBSERVER"; 
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SIGN_IN_WITH_EMAIL_PASS = "SIGN_IN_WITH_EMAIL_PASS";
export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE";
export const SIGN_IN_WITH_GITHUB = "SIGN_IN_WITH_GITHUB";
export const SIGN_OUT = 'SIGN_OUT';
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//blogs action types

export const POST_BLOGS = "POST_BLOGS";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";