//user Auth action types
export const CREATE_USER_WITH_EMAIL_PASS = "CREATE_USER_WITH_EMAIL_PASS";
export const AUTH_STATUS_OBSERVER = "AUTH_STATUS_OBSERVER"; 
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SIGN_IN_WITH_EMAIL_PASS = "SIGN_IN_WITH_EMAIL_PASS";
export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE";
export const SIGN_IN_WITH_GITHUB = "SIGN_IN_WITH_GITHUB";
export const SIGN_OUT = 'SIGN_OUT';
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const FETCH_UPDATED_USER_DATA ="FETCH_UPDATED_USER_DATA";
export const START_LOADING_UPDATE_USER = "START_LOADING_UPDATE_USER"
export const STOP_LOADING_UPDATE_USER = "STOP_LOADING_UPDATE_USER"

//blogs action types

export const POST_BLOGS = "POST_BLOGS";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const START_LOADING_FOR_BLOGS ="START_LOADING_FOR_BLOGS"
export const STOP_LOADING_FOR_BLOGS ="STOP_LOADING_FOR_BLOGS "
export const LOAD_BLOGS = "LOAD_BLOGS";
export const SELECT_BLOG ="SELECT_BLOG";
export const FETCH_USER_BLOGS ="FETCH_USER_BLOGS"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const SET_UPDATE_SUCCESS_FLAG = "SET_UPDATE_SUCCESS_FLAG";
export const DELETE_A_BLOG = "DELETE_A_BLOG";
export const DELETE_BLOG_FLAG = "DELETE_BLOG_FLAG";